info:
  app:
    name: Spring Boot Perks
    version: 1-0-0-SNAPSHOT

server:
  port: 8091
# actuator  properties configuration

management:
  security:
    enabled: false  # disabled security  for end points , so it can  be viewed to all
  endpoints:
      web:
        exposure:
          include: "*"  # will allow all
          #include : info ,health
      jmx:
        exposure:
          include: "*"  # will allow all
          #exclude : "env" // beans etc ..
      enpoint:
        shutdown:
          enabled: true # this one  by default  it is false

# http://localhost:8091/actuator - generic base path to access all



# profiles related configuration
spring:
  profile-testing-key: techinterface - no profiles set  .


# Logging Hierarchy Level
# ALL -> TRACE -> DEBUG -> INFO -> WARN-> ERROR -> FATAL -> OFF
# For color code display
# -spring.output.ansi.enabled=ALWAYS
# You can configure package wise log levels
# -com.techinterface.controller : DEBUG
logging:
  level:
#   ROOT: INFO
    ROOT: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: "C:/Users/Client/Documents/IdeaProjects/Spring-boot-swagger-config/Spring-Boot/src/main/resources/logs/Spring-Boot-Perks.log"
    max-size: 10MB
    clean-history-on-start: true

#    spring:
#      output:
#        ansi:
#         enabled: ALWAYS